### ISSUE TITLE
Issues working with react logging in

### ISSUE THREAD

**Issue by Eldgar** [wharfkit/web-ui-renderer#20]
//I am using this code in a basic react app

const [session, setSession] = useState(null);
  const [ui, setUi] = useState(null);
  //const [sessionKit, setSessionKit] = useState(null);
  const anchor = new WalletPluginAnchor();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setUi(new WebUIRenderer({ id: "login" }).appendDialogElement())
      }
    }, []);

    const sessionKit = new SessionKit({
      appName: 'demo',
      chains: [
        //Chain config
      ],
      ui,
      walletPlugins: [
          new WalletPluginAnchor(),
          new WalletPluginCloudWallet(),
      ],
    })

 
    async function login() {
      console.log("sessionKit ", sessionKit)
        const response = await sessionKit.login();
        setSession(response.session);
        console.log(session)
    }

//This code doesn't work and gives me the error 
Uncaught (in promise) Error: An instance of a UserInterface must be provided to utilize the login method.
    at SessionKit.login (kit.ts:150:19)
    at login (App.jsx:67:43)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)

however when i delete .appendDialogElement()  and save the code the login modal will pop up.
If I refresh the page with this code then it stops working and i need to add the .appendDialogElement() to make it work again.

useEffect(() => {
    if (typeof window !== 'undefined') {
      setUi(new WebUIRenderer({ id: "login" }))
      }
    }, []);

Maybe not an issue and just something stupid I am not doing, but just putting it out there

**Comment by Eldgar** [comment]
should have read the Nextjs issue changed code, seems to be working fine now

//no useState
const ui = new WebUIRenderer()

useEffect(() => {
        ui.appendDialogElement()
      }, []);
